services:
  graphrag:
    # Build the image using the Dockerfile in this directory
    build:
      context: .
      dockerfile: Dockerfile

    # Mount the entire repo into the container
    volumes:
      - ./:/GraphRAG-internship-Diego

    # Set the working directory inside the container
    working_dir: /GraphRAG-internship-Diego

    # Expose the Jupyter Notebook server on port 8888
    ports:
      - "8888:8888"

    # Allow interactive shell access
    stdin_open: true # -i
    tty: true # -t 

    # Start the Jupyter Notebook server
    command: [ "jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", --NotebookApp.token='', --NotebookApp.password='' ]
