preprocessing_params:
  keyterm_mincount: 5
  uniqueact_mincount: 2
  n_similarity_edges: 10

model:
  model_name: "GraphSAGE_V3_mean"
  model_channels: [1024, 1024, 512]

loader_params:
  num_neighbors: [5, 5]
  batch_size: 256
  shuffle: true

input_data:
  graph_file_name: "BSARD_dataset/intermediate/G_semantic.pkl" 

optimizer_params:
  learning_rate: 0.0005

training_params:
  num_epochs: 8

bundle_tag: "BSARD_test"