model_params:
  channels: [1024, 896, 768]
  num_layers: 2

loader_params:
  num_neighbors: [25, 50]
  batch_size: 512
  shuffle: true

input_data:
  graph_file_name: "BSARD_dataset/base_document_graph_wsem_V2.pkl" #"RIZIV_hackathon_main/base_hybrid_graph.pkl"
  embedding_dim: 1536 # BGE-M3: 1024; (OAI) text-embedding-3-small: 1536

optimizer_params:
  learning_rate: 0.0025

training_params:
  num_epochs: 10