model_params:
  channels: [1024, 768, 512]

loader_params:
  num_neighbors: [15, 15]
  batch_size: 256
  shuffle: true

input_data:
  graph_file_name: "RIZIV_hackathon_main/RIZIV_base_hybrid_graph_wsem.pkl" 

optimizer_params:
  learning_rate: 0.0005

training_params:
  num_epochs: 10

bundle_tag: "RIZIV_test"