model_params:
  channels: [1024, 1024]

loader_params:
  num_neighbors: [6]
  batch_size: 256
  shuffle: true

input_data:
  graph_file_name: "BSARD_dataset/intermediate/G_semantic.pkl" 

optimizer_params:
  learning_rate: 0.0005

training_params:
  num_epochs: 8

bundle_tag: "BSARD_test"