model_params:
  channels: [1024, 768, 512]
  num_layers: 2

loader_params:
  num_neighbors: [50, 150]
  batch_size: 512
  shuffle: true

input_data:
  graph_file_name: "BSARD_dataset/base_document_graph_wsem.pkl" #"RIZIV_hackathon_main/base_hybrid_graph.pkl"
  embedding_dim: 1536 # BGE-M3: 1024; (OAI) text-embedding-3-small: 1536

optimizer_params:
  learning_rate: 0.001

training_params:
  num_epochs: 20