preprocessing_params:
  keyterm_mincount: 6
  uniqueact_mincount: 4
  n_similarity_edges: 2

model:
  model_name: "GraphSAGE_V3_max"
  model_channels: [1024, 1024]

loader_params:
  num_neighbors: [5]
  batch_size: 256
  shuffle: true

input_data:
  graph_file_name: "BSARD_dataset/intermediate/G_pretraining.pkl" 

optimizer_params:
  learning_rate: 0.0005

training_params:
  num_epochs: 5

bundle_tag: "POST_TRIPLE_POSITIVE"