model_params:
  channels: [1024, 768, 512]

loader_params:
  num_neighbors: [15, 15]
  batch_size: 256
  shuffle: true

input_data:
  graph_file_name: "BSARD_dataset/base_document_graph_wsem_V2.pkl" 

optimizer_params:
  learning_rate: 0.0005

training_params:
  num_epochs: 2

bundle_tag: "bsard_V2"