model_params:
  channels: [1024, 768, 640]
  num_layers: 2

loader_params:
  num_neighbors: [15, 15]
  batch_size: 256
  shuffle: true

input_data:
  graph_file_name: "BSARD_dataset/base_document_graph_wsem_V2.pkl" 
  embedding_dim: 1024 # BGE-M3: 1024; (OAI) text-embedding-3-small: 1536

optimizer_params:
  learning_rate: 0.00001

training_params:
  num_epochs: 2

bundle_tag: "bsard_V2"