model_params:
  channels: [1024, 512, 256]
  num_layers: 2

loader_params:
  num_neighbors: [50, 150]
  batch_size: 512
  shuffle: true

input_data:
  graph_file_name: "riziv_dataset/base_hybrid_graph.pkl"
  embedding_dim: 1024 # BGE-M3: 1024; (OAI) text-embedding-3-small: 1536

optimizer_params:
  learning_rate: 0.001

training_params:
  num_epochs: 50